version: "3.0"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: sistemadb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432